// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw285ntg-qI_YivctmDW4B_hZCy6s6Bls',
    appId: '1:8671864719:web:5204a22752cce02b2fcdfa',
    messagingSenderId: '8671864719',
    projectId: 'socialapp-3b0e4',
    authDomain: 'socialapp-3b0e4.firebaseapp.com',
    storageBucket: 'socialapp-3b0e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9RKID2V7N-OffWqUzF5xKosGmdp3wee0',
    appId: '1:8671864719:android:f811f06808990eb12fcdfa',
    messagingSenderId: '8671864719',
    projectId: 'socialapp-3b0e4',
    storageBucket: 'socialapp-3b0e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBof7_v15nl5mpJh2nU4Ne5tN-Hvb__8hs',
    appId: '1:8671864719:ios:1ed2476da7f825492fcdfa',
    messagingSenderId: '8671864719',
    projectId: 'socialapp-3b0e4',
    storageBucket: 'socialapp-3b0e4.appspot.com',
    iosClientId: '8671864719-d2uoa6eb93oeulo3gb1jpceg8braha9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBof7_v15nl5mpJh2nU4Ne5tN-Hvb__8hs',
    appId: '1:8671864719:ios:1ed2476da7f825492fcdfa',
    messagingSenderId: '8671864719',
    projectId: 'socialapp-3b0e4',
    storageBucket: 'socialapp-3b0e4.appspot.com',
    iosClientId: '8671864719-d2uoa6eb93oeulo3gb1jpceg8braha9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );
}
